"""Initial migration with User and StudentProfile models

Revision ID: 0fbfabe64a49
Revises: 
Create Date: 2026-03-13 15:33:09.077632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fbfabe64a49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_is_admin'), ['is_admin'], unique=False)

    op.create_table('student_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('index_number', sa.String(length=50), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('field_of_study', sa.String(length=200), nullable=False),
    sa.Column('graduation_date', sa.Date(), nullable=False),
    sa.Column('work_experience', sa.Text(), nullable=True),
    sa.Column('projects', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('availability', sa.String(length=100), nullable=True),
    sa.Column('locations', sa.String(length=255), nullable=True),
    sa.Column('resume_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_profile_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_profile_field_of_study'), ['field_of_study'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_profile_institution'), ['institution'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_profile_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_profile_user_id'))
        batch_op.drop_index(batch_op.f('ix_student_profile_institution'))
        batch_op.drop_index(batch_op.f('ix_student_profile_field_of_study'))
        batch_op.drop_index(batch_op.f('ix_student_profile_email'))

    op.drop_table('student_profile')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_is_admin'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
